#server:
#  #  port: 8091
#  port: ${PORT:${SERVER_PORT:0}}
#spring:
#  application:
#    name: ms-proveedor-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms-proveedor
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html
#
##eureka:
##  client:
##    serviceUrl:
##      defaultZone: http://localhost:8090/eureka
##  instance:
##    hostname: localhost
#eureka:
#  client:
#    serviceUrl:
#      #defaultZone: http://localhost:8090/eureka
#      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
#  instance:
#    #hostname: localhost
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#

############



#server:
#
#  port: ${PORT:${SERVER_PORT:0}}
#
#spring:
#  application:
#    name: ms-proveedor-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms-proveedor
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html
#
#eureka:
#  client:
#    serviceUrl:
#      #defaultZone: http://localhost:8090/eureka
#      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
#  instance:
#    #hostname: localhost
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#
####################

server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: ms-proveedor-service

  datasource:
    url: jdbc:mysql://localhost:3306/ms-proveedor
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# Configuración de Management/Actuator para Health Check
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  server:
    port: ${server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
    healthcheck:
      enabled: true
    # Configuración para clientes que se registran
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Configuración específica para puerto dinámico
    prefer-ip-address: true
    # Health check configuración
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    # Configuración de lease para renovación más frecuente
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30